# Generated by Django 4.2.4 on 2023-08-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_forumroom_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumroom',
            name='topic',
        ),
    ]
