# Generated by Django 4.2.4 on 2023-08-15 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_forumroom_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumroom',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topic'),
        ),
    ]
